// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addresses": {
            "post": {
                "description": "Создаёт новый адрес в системе на основе переданных данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addresses"
                ],
                "summary": "Создать новый адрес",
                "parameters": [
                    {
                        "description": "Данные адреса для создания",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.AddressRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Адрес успешно создан",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.AddressResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибки валидации полей или некорректный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при сохранении адреса",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/addresses/{id}": {
            "get": {
                "description": "Возвращает полные данные адреса по уникальному идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addresses"
                ],
                "summary": "Получить адрес",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID адреса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Адрес успешно получен",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.AddressResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Адрес не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении адреса",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет адрес по уникальному идентификатору UUID",
                "tags": [
                    "addresses"
                ],
                "summary": "Удалить адрес",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID адреса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Адрес успешно удалён"
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Адрес не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при удалении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Возвращает список всех категорий в системе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Получить список категорий",
                "responses": {
                    "200": {
                        "description": "Список категорий успешно получен",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hardware_store_internal_web_dto.CategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении списка",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новую категорию в системе на основе переданных данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Создать новую категорию",
                "parameters": [
                    {
                        "description": "Данные категории для создания",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.CategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Категория успешно создана",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибки валидации полей или некорректный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при сохранении категории",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "description": "Возвращает полные данные категории по уникальному идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Получить категорию",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Категория успешно получена",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Категория не найдена",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении категории",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Обновляет данные категории по уникальному идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Обновить категорию",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновлённые данные категории",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.CategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Категория успешно обновлена",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный UUID или ошибки валидации данных",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Категория не найдена",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при обновлении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет категорию по уникальному идентификатору UUID",
                "tags": [
                    "categories"
                ],
                "summary": "Удалить категорию",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Категория успешно удалена"
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Категория не найдена",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при удалении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients": {
            "get": {
                "description": "Возвращает список всех клиентов в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Получить список всех клиентов",
                "responses": {
                    "200": {
                        "description": "Список клиентов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hardware_store_internal_web_dto.ClientResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт нового клиента вместе с адресом",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Создание клиента",
                "parameters": [
                    {
                        "description": "Данные клиента",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Клиент успешно создан",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ClientResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/search": {
            "get": {
                "description": "Возвращает информацию о клиенте по имени и фамилии",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Получить клиента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя клиента",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Фамилия клиента",
                        "name": "surname",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ClientResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Клиент не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "put": {
                "description": "Обновляет адрес клиента по его уникальному идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Обновить клиента",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID клиента",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные адреса для обновления",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.AddressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Адрес успешно обновлён"
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Клиент не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет клиента по его уникальному идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Удаление клиента",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID клиента",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Клиент не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/images/{id}": {
            "get": {
                "description": "Возвращает бинарные данные изображения по уникальному идентификатору",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Получить изображение по ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID изображения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Бинарные данные изображения"
                    },
                    "400": {
                        "description": "Невалидный формат UUID изображения",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Изображение не найдено",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении изображения",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет существующее изображение новыми бинарными данными",
                "consumes": [
                    "application/octet-stream"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Обновить изображение",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID изображения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Бинарные данные изображения",
                        "name": "image",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Изображение успешно обновлено"
                    },
                    "400": {
                        "description": "Невалидный формат UUID или некорректные данные изображения",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Изображение не найдено",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при обновлении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет изображение по уникальному идентификатору UUID",
                "tags": [
                    "images"
                ],
                "summary": "Удалить изображение",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID изображения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Изображение успешно удалено"
                    },
                    "400": {
                        "description": "Невалидный формат UUID изображения",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Изображение не найдено",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при удалении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Возвращает список всех продуктов в системе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получить список продуктов",
                "responses": {
                    "200": {
                        "description": "Список продуктов успешно получен",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hardware_store_internal_web_dto.ProductResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении списка",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новый продукт в системе на основе переданных данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Создать новый продукт",
                "parameters": [
                    {
                        "description": "Данные продукта для создания",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Продукт успешно создан",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибки валидации полей или некорректный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при сохранении продукта",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Возвращает полные данные продукта по уникальному идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получить продукт",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID продукта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Продукт успешно получен",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Продукт не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении продукта",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет продукт по уникальному идентификатору UUID",
                "tags": [
                    "products"
                ],
                "summary": "Удалить продукт",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID продукта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Продукт успешно удалён"
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Продукт не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при удалении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}/image": {
            "get": {
                "description": "Возвращает изображение продукта по его уникальному идентификатору",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Получить изображение продукта",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID продукта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Бинарные данные изображения"
                    },
                    "400": {
                        "description": "Невалидный формат UUID продукта",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Изображение не найдено",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении изображения",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Загружает новое изображение для указанного продукта",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Загрузить изображение для продукта",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID продукта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Бинарные данные изображения",
                        "name": "image",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Изображение успешно загружено",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ImageResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат UUID продукта или некорректные данные изображения",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при сохранении изображения",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}/stock": {
            "put": {
                "description": "Обновляет доступное количество товара на складе для указанного продукта",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Обновить количество товара на складе",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID продукта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новое количество товара",
                        "name": "stock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.UpdateStockCountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Количество товара успешно обновлено",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат запроса, отрицательное количество или недостаточный остаток",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Продукт не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при обновлении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/suppliers": {
            "get": {
                "description": "Возвращает список всех поставщиков в системе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Получить список поставщиков",
                "responses": {
                    "200": {
                        "description": "Список поставщиков успешно получен",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hardware_store_internal_web_dto.SupplierResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении списка",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт нового поставщика вместе с его адресом в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Создать нового поставщика",
                "parameters": [
                    {
                        "description": "Данные поставщика для создания",
                        "name": "supplier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.SupplierRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Поставщик успешно создан",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.SupplierResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибки валидации полей или некорректный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при сохранении поставщика",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/suppliers/{id}": {
            "get": {
                "description": "Возвращает полные данные поставщика по уникальному идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Получить поставщика",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID поставщика",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Поставщик успешно получен",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.SupplierResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Поставщик не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при получении поставщика",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет адрес поставщика по его уникальному идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Обновить адрес поставщика",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID поставщика",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновлённые данные адреса",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.AddressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Адрес поставщика успешно обновлён"
                    },
                    "400": {
                        "description": "Невалидный формат UUID или ошибки валидации данных",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Поставщик не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при обновлении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет поставщика по уникальному идентификатору UUID",
                "tags": [
                    "suppliers"
                ],
                "summary": "Удалить поставщика",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID поставщика",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Поставщик успешно удалён"
                    },
                    "400": {
                        "description": "Невалидный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Поставщик не найден",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при удалении",
                        "schema": {
                            "$ref": "#/definitions/hardware_store_internal_web_dto.InternalErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hardware_store_internal_web_dto.AddressRequest": {
            "description": "Запрос на создание нового адреса с информацией о стране, городе и улице",
            "type": "object",
            "required": [
                "city",
                "country",
                "street"
            ],
            "properties": {
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Москва"
                },
                "country": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Россия"
                },
                "street": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Технопарк, 15"
                }
            }
        },
        "hardware_store_internal_web_dto.AddressResponse": {
            "description": "Данные адреса включая информацию о местоположении",
            "type": "object",
            "properties": {
                "address_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "city": {
                    "type": "string",
                    "example": "Москва"
                },
                "country": {
                    "type": "string",
                    "example": "Россия"
                },
                "street": {
                    "type": "string",
                    "example": "Технопарк, 15"
                }
            }
        },
        "hardware_store_internal_web_dto.CategoryRequest": {
            "description": "Запрос на создание новой категории товаров",
            "type": "object",
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Холодильники"
                }
            }
        },
        "hardware_store_internal_web_dto.CategoryResponse": {
            "description": "Данные категории включая уникальный идентификатор и название",
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "Холодильники"
                },
                "category_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "hardware_store_internal_web_dto.ClientRequest": {
            "description": "Запрос на создание нового товара с категорией, ценой и информацией о поставщике",
            "type": "object",
            "required": [
                "name",
                "surname"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/hardware_store_internal_web_dto.AddressRequest"
                },
                "birthday": {
                    "type": "string",
                    "example": "1999-01-01"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female"
                    ],
                    "example": "male"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Иван"
                },
                "surname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Иванов"
                }
            }
        },
        "hardware_store_internal_web_dto.ClientResponse": {
            "description": "Данные клиента включая дату регистрации и ссылку на адрес",
            "type": "object",
            "properties": {
                "address_uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "birthday": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registration_date": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "hardware_store_internal_web_dto.ImageResponse": {
            "description": "Данные изображения включая уникальный идентификатор",
            "type": "object",
            "properties": {
                "image_id": {
                    "type": "string",
                    "example": "b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22"
                }
            }
        },
        "hardware_store_internal_web_dto.InternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "hardware_store_internal_web_dto.NotFoundErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "client not found"
                }
            }
        },
        "hardware_store_internal_web_dto.ProductRequest": {
            "description": "Запрос на обновление количества товара на складе",
            "type": "object",
            "required": [
                "available_stock",
                "category_id",
                "name",
                "price",
                "supplier_id"
            ],
            "properties": {
                "available_stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 15
                },
                "category_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Холодильник Samsung RB38A7861B1"
                },
                "price": {
                    "type": "number",
                    "example": 75990
                },
                "supplier_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "hardware_store_internal_web_dto.ProductResponse": {
            "description": "Полная информация о товаре включая цену, остатки и информацию о поставщике",
            "type": "object",
            "required": [
                "available_stock",
                "last_update_date",
                "name",
                "price",
                "product_id"
            ],
            "properties": {
                "available_stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "category": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "image": {
                    "type": "string",
                    "example": "b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22"
                },
                "last_update_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "price": {
                    "type": "number"
                },
                "product_id": {
                    "type": "string",
                    "example": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"
                },
                "supplier": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "hardware_store_internal_web_dto.SupplierRequest": {
            "description": "Запрос на создание нового поставщика с контактной информацией и адресом",
            "type": "object",
            "required": [
                "name",
                "phone_number"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/hardware_store_internal_web_dto.AddressRequest"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "ООО 'ТехноСнаб'"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79561234567"
                }
            }
        },
        "hardware_store_internal_web_dto.SupplierResponse": {
            "description": "Данные поставщика включая контактную информацию и ссылку на адрес",
            "type": "object",
            "properties": {
                "address_uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "ООО 'ТехноСнаб'"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79561234567"
                },
                "supplier_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "hardware_store_internal_web_dto.UpdateStockCountRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "hardware_store_internal_web_dto.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid uuid format"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hardware Store API",
	Description:      "REST API для магазина бытовой техники",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	//LeftDelim:        "{{",
	//RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
